Fix progress update

diff --git a/sh/install-cmd b/sh/install-cmd
--- a/sh/install-cmd
+++ b/sh/install-cmd
@@ -1,44 +1,41 @@
 #!/bin/sh
-echo "🚀 Downloading...";
+echo "🚀 Downloading..."
 rm -rf Srt2BilibiliKit
 git clone https://github.com/ApolloZhu/Srt2BilibiliKit.git
-if [[ $? != 0 ]]; then 
-    echo "❌ Failed to download";
-    exit 1;
+if [[ $? != 0 ]]; then
+    echo "❌ Failed to download"
+    exit 1
 fi
 cd Srt2BilibiliKit
 
-echo "🛠  Building...";
+echo "🛠  Building..."
 swift package clean
-if [[ $? != 0 ]]; then 
-    echo "❌ Failed to build";
-    exit 1;
+if [[ $? != 0 ]]; then
+    echo "❌ Failed to clean"
+    exit 1
 fi
 swift build -c release
-if [[ $? != 0 ]]; then 
-    echo "❌ Failed to build";
-    exit 1;
+if [[ $? != 0 ]]; then
+    echo "❌ Failed to build"
+    exit 1
 fi
 
-echo "🗑  Clean up...";
+echo "💼  Installing..."
 cp .build/release/Srt2Bilibili-cli /usr/local/bin/s2bkit
-if [[ $? != 0 ]]; then 
+if [[ $? != 0 ]]; then
     cp .build/release/Srt2Bilibili-cli ../s2bkit
-    MODE="LIMITED";
+    MODE="LIMITED"
 fi
 cd ..
 rm -rf Srt2BilibiliKit
 
 if [[ $MODE == "LIMITED" ]]; then
     export PATH=$PWD:"${PATH}"
+    echo "⚠️  Adding $PWD to your \$PATH is recommended"
     chmod +x s2bkit
 fi
 s2bkit
-if [[ $? != 0 ]]; then 
-    echo "❌ Failed to execute";
-    exit 1;
-fi
-echo "✅ Done!";
-if [[ $MODE == "LIMITED" ]]; then
-    echo "⚠️  Adding $PWD to your \$PATH is recommended";
+if [[ $? != 0 ]]; then
+    echo "❌ Failed to execute"
+    exit 1
 fi
